### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [plum2929/my_scenery#98]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

```
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## READMEから課題解決する実装がされているか&動いている
READMEを元に挙動確認を行い、問題ないことを確認しました。

## 静的コードチェックが入っている
大まかに確認しましたが問題なさそうなことを確認しました。

## 就活において十分な技術力を示せる機能を実装しているか
・一定数の技術力を示せる状態にあるかと思いました。
・ルーティングに関して：resourceベースのルーティングに近づけられないか考えて修正できると尚良いでしょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・触った感じ特に違和感を感じるところは無かったです。ただ「気になる」に含まれた画像を外したい場合はどうすればいいのか、時間の経過で「気になる」から消えてしまうのかどうかが気になりました。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by plum2929** [comment]
@Tsuchiya2 

レビューいただきありがとうございます。

> ルーティングに関して：resourceベースのルーティングに近づけられないか考えて修正できると尚良いでしょう。

もう少し綺麗な形にできないか考えてみます！

> 「気になる」に含まれた画像を外したい場合はどうすればいいのか、時間の経過で「気になる」から消えてしまうのかどうかが気になりました。

「気になる」の削除機能は、UIの面でどのように実現するのが良いか検討中のため後回しにしておりました。
こちらは本リリース時に追加予定です。

> 本リリースまでのスケジュールを教えていただけますでしょうか？

9月末までに残りの機能を実装し、本リリースができればと考えております。

**Comment by Tsuchiya2** [comment]
回答ありがとうございます。
引き続き頑張ってください。

**Comment by Tsuchiya2** [comment]
==============
@plum2929 

追記です。
就活に望む前までにREADMEをRUNTEQ向けのものではなく、自分が就活に取り組む上での武器になるように手直ししておくと良いと思います。
